workflows:
  ios-release:
    name: iOS Release Safebrok
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: "Codemagic Safebrok"

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - safebrok_appstore_push
        certificates:
          - safebrok_distribution

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Validate Dart code
        script: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Test App Review roles
        script: flutter test test/app_role_test.dart

      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Set up code signing
        script: |
          xcode-project use-profiles --project ios/Runner.xcodeproj

      - name: Build IPA
        script: |
          flutter build ipa --release \
            -t lib/main.dart \
            --build-name=1.1.0 \
            --build-number=9 \
            --export-options-plist=/Users/builder/export_options.plist
          echo "BUSCANDO IPA..."
          find build -name "*.ipa" -print

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
