-- SafeBrok · Incorporaciones. Ejecutar después de 20260810_rls_app_review.sql.
begin;
create extension if not exists pgcrypto;
do $$ begin create type public.incorporacion_estado as enum ('BORRADOR','ENVIADO','EN_REVISION','CORRECCION_REQUERIDA','DOCUMENTACION_VALIDADA','CONTRATO_DISPONIBLE','PENDIENTE_FIRMA','CONTRATO_FIRMADO','ALTA_COMPLETADA'); exception when duplicate_object then null; end $$;
do $$ begin create type public.incorporacion_documento_tipo as enum ('DNI_ANVERSO','DNI_REVERSO','FOTO_CORPORATIVA','CERTIFICADO_TITULARIDAD','CV','CONTRATO','CONTRATO_FIRMADO'); exception when duplicate_object then null; end $$;
do $$ begin create type public.incorporacion_documento_estado as enum ('PENDIENTE','SUBIDO','VALIDADO','CORRECCION_REQUERIDA'); exception when duplicate_object then null; end $$;

create table if not exists public.incorporaciones(
 id uuid primary key default gen_random_uuid(), candidato_captacion_id text,
 solicitante_auth_id uuid not null default auth.uid(), responsable_id uuid not null references public.usuarios(id),
 figura text not null check(figura in('agente','jefe_equipo','jefe_ventas','director_zona','director_nacional','administracion')),
 nombre text not null,apellidos text not null,dni_nie text not null,direccion text not null,telefono text not null,email text not null,fecha_prevista_incorporacion date not null,
 estado public.incorporacion_estado not null default 'BORRADOR',observaciones_correccion text,contrato_generado_at timestamptz,
 usuario_creado_id uuid references public.usuarios(id),alta_preparada jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),enviado_at timestamptz,completado_at timestamptz,
 check(length(trim(dni_nie))>=5),check(position('@' in email)>1));
create unique index if not exists incorporaciones_candidato_activo_uidx on public.incorporaciones(candidato_captacion_id) where candidato_captacion_id is not null and estado<>'ALTA_COMPLETADA';
create unique index if not exists incorporaciones_dni_activo_uidx on public.incorporaciones(upper(regexp_replace(dni_nie,'\s','','g'))) where estado<>'ALTA_COMPLETADA';
create index if not exists incorporaciones_estado_idx on public.incorporaciones(estado,updated_at desc);

create table if not exists public.incorporacion_documentos(id uuid primary key default gen_random_uuid(),incorporacion_id uuid not null references public.incorporaciones(id) on delete cascade,tipo public.incorporacion_documento_tipo not null,storage_path text not null,nombre_archivo text not null,mime_type text,tamano_bytes bigint,estado public.incorporacion_documento_estado not null default 'SUBIDO',observaciones text,subido_por uuid not null default auth.uid(),revisado_por uuid,revisado_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(incorporacion_id,tipo));
create table if not exists public.incorporacion_historial(id bigint generated always as identity primary key,incorporacion_id uuid not null references public.incorporaciones(id) on delete cascade,actor_auth_id uuid,accion text not null,estado_anterior public.incorporacion_estado,estado_nuevo public.incorporacion_estado,detalle jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists incorporacion_historial_idx on public.incorporacion_historial(incorporacion_id,created_at desc);

create or replace function public.incorporacion_role_level(v text)returns integer language sql immutable set search_path='' as $$select case lower(trim(replace(coalesce(v,''),'-','_')))when'agente'then 1 when'jefe_equipo'then 2 when'jefe_ventas'then 3 when'director_zona'then 4 when'director_nacional'then 5 when'administracion'then 6 else 0 end$$;
create or replace function public.incorporacion_can_assign(target_user_id uuid,target_role text)returns boolean language plpgsql stable security definer set search_path='' as $$declare me public.usuarios%rowtype;target public.usuarios%rowtype;my_role text;begin select * into me from public.usuarios where auth_id=auth.uid() limit 1;select * into target from public.usuarios where id=target_user_id limit 1;if me.id is null or target.id is null then return false;end if;my_role:=lower(trim(replace(coalesce(me.rol_usuario,''),'-','_')));if my_role='administracion'then return true;end if;if public.incorporacion_role_level(target_role)<=0 or public.incorporacion_role_level(target_role)>=public.incorporacion_role_level(target.rol_usuario)then return false;end if;return target.id=me.id or public.app_can_access_user_id(target.id);end$$;
create or replace function public.incorporacion_can_access(e public.incorporaciones)returns boolean language sql stable security definer set search_path='' as $$select auth.uid()=e.solicitante_auth_id or public.app_can_manage_global() or public.app_can_access_user_id(e.responsable_id)$$;

create or replace function public.incorporacion_before_write()returns trigger language plpgsql security definer set search_path='' as $$begin new.updated_at:=now();if tg_op='INSERT'and not public.incorporacion_can_assign(new.responsable_id,new.figura)then raise exception'Figura o responsable fuera del ámbito permitido';end if;if tg_op='UPDATE'and old.contrato_generado_at is not null and(old.figura is distinct from new.figura or old.responsable_id is distinct from new.responsable_id)and not public.app_can_manage_global()then raise exception'Figura y responsable bloqueados desde la generación del contrato';end if;if tg_op='UPDATE'and(old.figura is distinct from new.figura or old.responsable_id is distinct from new.responsable_id)and not public.incorporacion_can_assign(new.responsable_id,new.figura)then raise exception'Figura o responsable fuera del ámbito permitido';end if;return new;end$$;
drop trigger if exists incorporacion_before_write_trg on public.incorporaciones;create trigger incorporacion_before_write_trg before insert or update on public.incorporaciones for each row execute function public.incorporacion_before_write();
create or replace function public.incorporacion_audit()returns trigger language plpgsql security definer set search_path='' as $$begin if tg_op='INSERT'then insert into public.incorporacion_historial(incorporacion_id,actor_auth_id,accion,estado_nuevo,detalle)values(new.id,auth.uid(),'EXPEDIENTE_CREADO',new.estado,jsonb_build_object('figura',new.figura,'responsable_id',new.responsable_id));elsif old.estado is distinct from new.estado then insert into public.incorporacion_historial(incorporacion_id,actor_auth_id,accion,estado_anterior,estado_nuevo)values(new.id,auth.uid(),'CAMBIO_ESTADO',old.estado,new.estado);elsif old.figura is distinct from new.figura or old.responsable_id is distinct from new.responsable_id then insert into public.incorporacion_historial(incorporacion_id,actor_auth_id,accion,estado_anterior,estado_nuevo,detalle)values(new.id,auth.uid(),'ASIGNACION_MODIFICADA',old.estado,new.estado,jsonb_build_object('figura_anterior',old.figura,'figura_nueva',new.figura,'responsable_anterior',old.responsable_id,'responsable_nuevo',new.responsable_id));else insert into public.incorporacion_historial(incorporacion_id,actor_auth_id,accion,estado_anterior,estado_nuevo)values(new.id,auth.uid(),'EXPEDIENTE_ACTUALIZADO',old.estado,new.estado);end if;return new;end$$;
drop trigger if exists incorporacion_audit_trg on public.incorporaciones;create trigger incorporacion_audit_trg after insert or update on public.incorporaciones for each row execute function public.incorporacion_audit();
create or replace function public.incorporacion_documento_audit() returns trigger language plpgsql security definer set search_path='' as $$
begin
 insert into public.incorporacion_historial(incorporacion_id,actor_auth_id,accion,detalle)
 values(new.incorporacion_id,auth.uid(),case when tg_op='INSERT' then 'DOCUMENTO_SUBIDO' else 'DOCUMENTO_ACTUALIZADO' end,jsonb_build_object('tipo',new.tipo,'estado',new.estado,'observaciones',new.observaciones));
 return new;
end $$;
drop trigger if exists incorporacion_documento_audit_trg on public.incorporacion_documentos;
create trigger incorporacion_documento_audit_trg after insert or update on public.incorporacion_documentos for each row execute function public.incorporacion_documento_audit();

create or replace function public.incorporacion_notify(target_auth uuid,title_text text,message_text text) returns void language plpgsql security definer set search_path='' as $$
begin
 insert into public.notificaciones(usuario_auth_id,tipo,titulo,mensaje,entidad_tipo,datos,leida,enviada_push,creado_en)
 values(target_auth,'incorporacion',title_text,message_text,'incorporacion','{}'::jsonb,false,false,now());
end $$;
create or replace function public.incorporacion_set_estado(p_id uuid,p_estado public.incorporacion_estado,p_observaciones text default null)returns public.incorporaciones language plpgsql security definer set search_path='' as $$
declare e public.incorporaciones%rowtype;missing integer;u record;
begin select * into e from public.incorporaciones where id=p_id for update;if e.id is null or not public.incorporacion_can_access(e)then raise exception'Expediente no accesible';end if;
if p_estado='ENVIADO'then if e.estado not in('BORRADOR','CORRECCION_REQUERIDA')then raise exception'Transición no permitida';end if;select count(*)into missing from(values('DNI_ANVERSO'),('DNI_REVERSO'),('FOTO_CORPORATIVA'),('CERTIFICADO_TITULARIDAD'),('CV'))r(tipo)where not exists(select 1 from public.incorporacion_documentos d where d.incorporacion_id=e.id and d.tipo::text=r.tipo);if missing>0 then raise exception'Faltan documentos obligatorios';end if;update public.incorporaciones set estado=p_estado,enviado_at=now(),observaciones_correccion=null where id=p_id returning * into e;for u in select auth_id from public.usuarios where lower(trim(replace(rol_usuario,'-','_')))in('administracion','director_nacional')loop perform public.incorporacion_notify(u.auth_id,'Nuevo expediente de incorporación',e.nombre||' '||e.apellidos||' está pendiente de revisión.');end loop;
elsif p_estado='CORRECCION_REQUERIDA'then if not public.app_can_manage_global()or nullif(trim(p_observaciones),'')is null then raise exception'Administración debe indicar observaciones';end if;update public.incorporaciones set estado=p_estado,observaciones_correccion=p_observaciones where id=p_id returning * into e;perform public.incorporacion_notify(e.solicitante_auth_id,'Corrección requerida',p_observaciones);
elsif p_estado in('EN_REVISION','DOCUMENTACION_VALIDADA','CONTRATO_DISPONIBLE','PENDIENTE_FIRMA','CONTRATO_FIRMADO','ALTA_COMPLETADA')then if not public.app_can_manage_global()and not(p_estado='CONTRATO_FIRMADO'and auth.uid()=e.solicitante_auth_id)then raise exception'Acción reservada a Administración';end if;if p_estado='DOCUMENTACION_VALIDADA'and exists(select 1 from public.incorporacion_documentos d where d.incorporacion_id=e.id and d.tipo::text in('DNI_ANVERSO','DNI_REVERSO','FOTO_CORPORATIVA','CERTIFICADO_TITULARIDAD','CV')and d.estado<>'VALIDADO')then raise exception'Hay documentos sin validar';end if;if p_estado in('CONTRATO_DISPONIBLE','PENDIENTE_FIRMA')and not exists(select 1 from public.incorporacion_documentos d where d.incorporacion_id=e.id and d.tipo='CONTRATO')then raise exception'Falta el contrato';end if;if p_estado='CONTRATO_FIRMADO'and not exists(select 1 from public.incorporacion_documentos d where d.incorporacion_id=e.id and d.tipo='CONTRATO_FIRMADO'and d.estado='SUBIDO')then raise exception'Debes subir una nueva versión del contrato firmado';end if;if p_estado='ALTA_COMPLETADA'and not exists(select 1 from public.incorporacion_documentos d where d.incorporacion_id=e.id and d.tipo='CONTRATO_FIRMADO')then raise exception'Falta el contrato firmado';end if;update public.incorporaciones set estado=p_estado,contrato_generado_at=case when p_estado in('CONTRATO_DISPONIBLE','PENDIENTE_FIRMA')then coalesce(contrato_generado_at,now())else contrato_generado_at end,completado_at=case when p_estado='ALTA_COMPLETADA'then now()else completado_at end,alta_preparada=case when p_estado='ALTA_COMPLETADA'then jsonb_build_object('nombre',nombre,'apellidos',apellidos,'email',lower(email),'rol_usuario',figura,'parent_id',responsable_id,'incorporacion_id',id)else alta_preparada end where id=p_id returning * into e;if p_estado='CONTRATO_DISPONIBLE'then perform public.incorporacion_notify(e.solicitante_auth_id,'Contrato disponible','El contrato está listo para firma.');end if;if p_estado='CONTRATO_FIRMADO'then for u in select auth_id from public.usuarios where lower(trim(replace(rol_usuario,'-','_')))in('administracion','director_nacional')loop perform public.incorporacion_notify(u.auth_id,'Contrato firmado recibido',e.nombre||' '||e.apellidos);end loop;end if;else raise exception'Transición no permitida';end if;return e;end$$;

create or replace function public.incorporacion_rechazar_contrato_firmado(p_id uuid,p_observaciones text)
returns public.incorporaciones language plpgsql security definer set search_path='' as $$
declare e public.incorporaciones%rowtype;
begin
 if not public.app_can_manage_global() then raise exception 'Acción reservada a Administración'; end if;
 if nullif(trim(p_observaciones),'') is null then raise exception 'Debes indicar el motivo del rechazo'; end if;
 select * into e from public.incorporaciones where id=p_id for update;
 if e.id is null then raise exception 'Expediente no encontrado'; end if;
 if e.estado not in ('PENDIENTE_FIRMA','CONTRATO_FIRMADO') then raise exception 'El contrato no está pendiente de revisión de firma'; end if;
 if not exists(select 1 from public.incorporacion_documentos d where d.incorporacion_id=e.id and d.tipo='CONTRATO_FIRMADO') then raise exception 'No existe contrato firmado para rechazar'; end if;
 update public.incorporacion_documentos set estado='CORRECCION_REQUERIDA',observaciones=trim(p_observaciones),revisado_por=auth.uid(),revisado_at=now(),updated_at=now() where incorporacion_id=e.id and tipo='CONTRATO_FIRMADO';
 update public.incorporaciones set estado='PENDIENTE_FIRMA',observaciones_correccion=trim(p_observaciones) where id=e.id returning * into e;
 perform public.incorporacion_notify(e.solicitante_auth_id,'Contrato firmado rechazado',trim(p_observaciones));
 return e;
end $$;
alter table public.incorporaciones enable row level security;alter table public.incorporacion_documentos enable row level security;alter table public.incorporacion_historial enable row level security;
drop policy if exists incorporaciones_select on public.incorporaciones;create policy incorporaciones_select on public.incorporaciones for select to authenticated using(public.incorporacion_can_access(incorporaciones));
drop policy if exists incorporaciones_insert on public.incorporaciones;create policy incorporaciones_insert on public.incorporaciones for insert to authenticated with check(solicitante_auth_id=auth.uid()and estado='BORRADOR'and public.incorporacion_can_assign(responsable_id,figura));
drop policy if exists incorporaciones_update on public.incorporaciones;create policy incorporaciones_update on public.incorporaciones for update to authenticated using(public.incorporacion_can_access(incorporaciones))with check(public.incorporacion_can_access(incorporaciones));
drop policy if exists documentos_select on public.incorporacion_documentos;create policy documentos_select on public.incorporacion_documentos for select to authenticated using(exists(select 1 from public.incorporaciones e where e.id=incorporacion_id and public.incorporacion_can_access(e)));
drop policy if exists documentos_insert on public.incorporacion_documentos;create policy documentos_insert on public.incorporacion_documentos for insert to authenticated with check(subido_por=auth.uid()and exists(select 1 from public.incorporaciones e where e.id=incorporacion_id and public.incorporacion_can_access(e)));
drop policy if exists documentos_update on public.incorporacion_documentos;create policy documentos_update on public.incorporacion_documentos for update to authenticated using(exists(select 1 from public.incorporaciones e where e.id=incorporacion_id and public.incorporacion_can_access(e))and(public.app_can_manage_global()or subido_por=auth.uid()))with check(exists(select 1 from public.incorporaciones e where e.id=incorporacion_id and public.incorporacion_can_access(e))and(public.app_can_manage_global()or(subido_por=auth.uid()and estado='SUBIDO')));
drop policy if exists historial_select on public.incorporacion_historial;create policy historial_select on public.incorporacion_historial for select to authenticated using(exists(select 1 from public.incorporaciones e where e.id=incorporacion_id and public.incorporacion_can_access(e)));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('incorporaciones','incorporaciones',false,15728640,array['application/pdf','image/jpeg','image/png','image/webp','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists incorporaciones_storage_select on storage.objects;create policy incorporaciones_storage_select on storage.objects for select to authenticated using(bucket_id='incorporaciones'and exists(select 1 from public.incorporaciones e where e.id::text=(storage.foldername(name))[1]and public.incorporacion_can_access(e)));
drop policy if exists incorporaciones_storage_insert on storage.objects;create policy incorporaciones_storage_insert on storage.objects for insert to authenticated with check(bucket_id='incorporaciones'and exists(select 1 from public.incorporaciones e where e.id::text=(storage.foldername(name))[1]and public.incorporacion_can_access(e)));
drop policy if exists incorporaciones_storage_update on storage.objects;create policy incorporaciones_storage_update on storage.objects for update to authenticated using(bucket_id='incorporaciones'and exists(select 1 from public.incorporaciones e where e.id::text=(storage.foldername(name))[1]and public.incorporacion_can_access(e)))with check(bucket_id='incorporaciones');
revoke all on function public.incorporacion_can_assign(uuid,text),public.incorporacion_set_estado(uuid,public.incorporacion_estado,text),public.incorporacion_rechazar_contrato_firmado(uuid,text)from public,anon;grant execute on function public.incorporacion_can_assign(uuid,text),public.incorporacion_set_estado(uuid,public.incorporacion_estado,text),public.incorporacion_rechazar_contrato_firmado(uuid,text)to authenticated;grant select,insert,update on public.incorporaciones,public.incorporacion_documentos to authenticated;grant select on public.incorporacion_historial to authenticated;
commit;
