import { createClient } from 'npm:@supabase/supabase-js@2';
type R=Record<string,unknown>;type U={id:string;auth_id:string|null;parent_id:string|null;rol_usuario:string|null;estado:string|null};
const H={'Content-Type':'application/json; charset=utf-8'},text=(v:unknown)=>String(v??'').trim(),norm=(v:unknown)=>text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const num=(v:unknown)=>{const s=text(v),x=Number(s.includes(',')?s.replaceAll('.','').replace(',','.'):s);return Number.isFinite(x)?x:0},active=(v:unknown)=>!['baja','inactivo','inactiva','bloqueado','bloqueada','desactivado','desactivada','suspendido','suspendida','eliminado','eliminada'].includes(norm(v));
const productive=(s:R)=>!['baja','extorno','anulada','anulado','anulacion','cancelada','cancelado'].some(x=>[s.estado,s.estado_poliza,s.tipo,s.tipo_movimiento,s.situacion].map(norm).join(' ').includes(x));
const premium=(s:R)=>{const p=norm(s.producto),auto=['auto','coche','vehicul','turismo','moto','camion'].some(x=>p.includes(x)),d=text(s.fecha_efecto).slice(0,10);return num(s.prima_anual_neta??s.prima_neta)*(auto && d >= '2026-08-27' ? 0 : 1)},isMix=(s:R)=>norm(s.producto).includes('deceso')||norm(s.producto).includes('vida');
const euro=(v:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(v),reply=(b:R,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
const madrid=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),g=(x:string)=>Number(p.find(y=>y.type===x)?.value??0);return{year:g('year'),month:g('month'),day:g('day'),hour:g('hour')}};
Deno.serve(async req=>{if(req.method!=='POST')return reply({ok:false},405);const secret=Deno.env.get('CRON_SECRET')??'',url=Deno.env.get('SUPABASE_URL')??'',key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'';if(!secret||req.headers.get('x-cron-secret')!==secret)return reply({ok:false,error:'No autorizado'},401);
try{const body=await req.json().catch(()=>({})) as {auth_id_prueba?:string;ignorar_fecha?:boolean},now=madrid();if(!body.ignorar_fecha&&now.hour!==9)return reply({ok:true,enviado:false,motivo:'Fuera de hora'});const today=now.year.toString().padStart(4,'0')+'-'+now.month.toString().padStart(2,'0')+'-'+now.day.toString().padStart(2,'0'),db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const {data:c,error:ce}=await db.from('cierres_produccion').select('id,fecha_desde,fecha_hasta').lte('fecha_desde',today).gte('fecha_hasta',today).limit(1).maybeSingle();if(ce)throw ce;if(!c)return reply({ok:true,enviado:false,motivo:'Sin cierre activo'});const date=text(c.fecha_hasta).split('-').map(Number),days=Math.round((Date.UTC(date[0],date[1]-1,date[2])-Date.UTC(now.year,now.month-1,now.day))/86400000);if(!body.ignorar_fecha&&days!==7)return reply({ok:true,enviado:false,dias_restantes:days});
const {data:ur,error:ue}=await db.from('usuarios').select('id,auth_id,parent_id,rol_usuario,estado');if(ue)throw ue;const all=((ur??[])as U[]).filter(u=>u.id&&u.auth_id&&active(u.estado)),users=body.auth_id_prueba?all.filter(u=>u.auth_id===body.auth_id_prueba):all,ch=new Map<string,U[]>();for(const u of all){if(!u.parent_id)continue;const a=ch.get(u.parent_id)??[];a.push(u);ch.set(u.parent_id,a)}const structure=(root:U)=>{const out=new Set<string>(),seen=new Set<string>(),stack=[root];while(stack.length){const u=stack.pop()!;if(seen.has(u.id))continue;seen.add(u.id);if(u.auth_id)out.add(u.auth_id);stack.push(...(ch.get(u.id)??[]))}return out};
const end=new Date(Date.UTC(date[0],date[1]-1,date[2]+1)).toISOString().slice(0,10),{data:sr,error:se}=await db.from('ventas').select('agente_auth_id,prima_anual_neta,prima_neta,producto,fecha_efecto,estado,estado_poliza,tipo,tipo_movimiento,situacion').gte('fecha_efecto',c.fecha_desde).lt('fecha_efecto',end);if(se)throw se;const totals=new Map<string,number>(),mixes=new Map<string,number>();for(const s of ((sr??[])as R[]).filter(productive)){const id=text(s.agente_auth_id),v=premium(s);if(!id)continue;totals.set(id,(totals.get(id)??0)+v);if(isMix(s))mixes.set(id,(mixes.get(id)??0)+v)}
let sent=0,bell=0,duplicates=0,noDevice=0,errors=0;for(const u of users){let total=0,mix=0;for(const id of structure(u)){total+=totals.get(id)??0;mix+=mixes.get(id)??0}const pct=total?mix/total*100:0,agent=norm(u.rol_usuario)==='agente',title=body.auth_id_prueba?'[PRUEBA] 7 días para el cierre':'7 días para el cierre',message=(agent?'Llevas':'Tu estructura lleva')+' '+euro(total)+' en primas y un mix Decesos + Vida del '+pct.toFixed(1)+' %. Queda una semana: vamos a por el mejor cierre.',data={tipo:'cierre_produccion',dias_restantes:'7',fecha_cierre:text(c.fecha_hasta),primas:total.toFixed(2),porcentaje_mix:pct.toFixed(2)};let nid='';
if(!body.auth_id_prueba){const {data:ex}=await db.from('notificaciones').select('id').eq('tipo','cierre_produccion_7_dias').eq('entidad_id',text(c.id)).eq('usuario_auth_id',u.auth_id!).maybeSingle();if(ex){duplicates++;continue}const {data:no,error:ie}=await db.from('notificaciones').insert({usuario_auth_id:u.auth_id,tipo:'cierre_produccion_7_dias',titulo:title,mensaje:message,entidad_tipo:'cierre_produccion',entidad_id:text(c.id),datos:{...data,primas_mix:mix.toFixed(2),alcance:agent?'propio':'estructura'},leida:false,enviada_push:false,creado_en:new Date().toISOString()}).select('id').single();if(ie){errors++;continue}nid=text(no.id);bell++}
const pr=await fetch(url+'/functions/v1/enviar-push',{method:'POST',headers:{Authorization:'Bearer '+key,apikey:key,'Content-Type':'application/json'},body:JSON.stringify({auth_id_destino:u.auth_id,incluir_superiores:false,titulo:title,mensaje:message,data})}),result=await pr.json().catch(()=>({})),ok=pr.ok&&(result as R).ok===true;if(ok)sent++;else if(pr.status===404)noDevice++;else errors++;if(nid)await db.from('notificaciones').update({enviada_push:ok,error_push:ok?null:JSON.stringify(result).slice(0,1000)}).eq('id',nid)}
return reply({ok:errors===0,dias_restantes:7,usuarios_evaluados:users.length,push_enviados:sent,avisos_campanita:bell,sin_dispositivo:noDevice,duplicados,errores},errors?207:200)}catch(e){console.error('notificar-cierre-7-dias',e);return reply({ok:false,error:e instanceof Error?e.message:String(e)},500)}});