create table if not exists public.portal_solicitudes_servicios (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  servicio text not null,
  estado text not null default 'nuevo',
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.portal_solicitudes_servicios enable row level security;

drop policy if exists portal_solicitudes_insert_own on public.portal_solicitudes_servicios;
create policy portal_solicitudes_insert_own
  on public.portal_solicitudes_servicios for insert to authenticated
  with check (auth.uid() = auth_user_id);

drop policy if exists portal_solicitudes_select_own on public.portal_solicitudes_servicios;
create policy portal_solicitudes_select_own
  on public.portal_solicitudes_servicios for select to authenticated
  using (auth.uid() = auth_user_id);

create index if not exists portal_solicitudes_auth_idx
  on public.portal_solicitudes_servicios(auth_user_id, created_at desc);