-- SafeBrok: cambio de figura con contrato, firma y validacion final.
begin;
create table if not exists public.cambios_rol(
 id uuid primary key default gen_random_uuid(), usuario_id uuid not null references public.usuarios(id), candidato_auth_id uuid not null,
 rol_anterior text not null, rol_nuevo text not null check(rol_nuevo in('administracion','director_nacional','director_zona','jefe_ventas','jefe_equipo','agente')),
 parent_anterior_id uuid references public.usuarios(id), parent_nuevo_id uuid references public.usuarios(id), iniciado_por_usuario_id uuid not null references public.usuarios(id),
 estado text not null default 'PENDIENTE_CONTRATO' check(estado in('PENDIENTE_CONTRATO','PENDIENTE_FIRMA','FIRMADO_PENDIENTE_VALIDACION','CORRECCION_REQUERIDA','APROBADO','RECHAZADO','CANCELADO')),
 contrato_path text,contrato_nombre text,contrato_firmado_path text,contrato_firmado_nombre text,observaciones text,
 contrato_enviado_at timestamptz,firmado_at timestamptz,aprobado_at timestamptz,aprobado_por_usuario_id uuid references public.usuarios(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists cambios_rol_usuario_abierto_uidx on public.cambios_rol(usuario_id) where estado not in('APROBADO','RECHAZADO','CANCELADO');
alter table public.cambios_rol enable row level security;
drop policy if exists cambios_rol_select on public.cambios_rol;
create policy cambios_rol_select on public.cambios_rol for select to authenticated using(public.app_can_manage_global() or candidato_auth_id=auth.uid());
create or replace function public.cambio_rol_publicar_contrato(p_id uuid,p_path text,p_nombre text) returns public.cambios_rol language plpgsql security definer set search_path='' as $$declare c public.cambios_rol%rowtype;begin if not public.app_can_manage_global() then raise exception 'Accion reservada a Administracion o Direccion Nacional';end if;update public.cambios_rol set contrato_path=p_path,contrato_nombre=p_nombre,estado='PENDIENTE_FIRMA',contrato_enviado_at=now(),observaciones=null,updated_at=now() where id=p_id and estado in('PENDIENTE_CONTRATO','CORRECCION_REQUERIDA') returning * into c;if c.id is null then raise exception 'El expediente no admite el envio del contrato';end if;insert into public.notificaciones(usuario_auth_id,tipo,titulo,mensaje,entidad_tipo,datos,leida,enviada_push,creado_en)values(c.candidato_auth_id,'cambio_rol','Contrato de cambio de figura disponible','Revisa, firma y adjunta el contrato para continuar.','cambio_rol',jsonb_build_object('cambio_rol_id',c.id),false,false,now());return c;end$$;
create or replace function public.cambio_rol_enviar_firmado(p_id uuid,p_path text,p_nombre text) returns public.cambios_rol language plpgsql security definer set search_path='' as $$declare c public.cambios_rol%rowtype;u record;begin select * into c from public.cambios_rol where id=p_id for update;if c.id is null or c.candidato_auth_id<>auth.uid() then raise exception 'Expediente no accesible';end if;if c.estado not in('PENDIENTE_FIRMA','CORRECCION_REQUERIDA') then raise exception 'El contrato no esta pendiente de firma';end if;update public.cambios_rol set contrato_firmado_path=p_path,contrato_firmado_nombre=p_nombre,estado='FIRMADO_PENDIENTE_VALIDACION',firmado_at=now(),observaciones=null,updated_at=now() where id=p_id returning * into c;for u in select auth_id from public.usuarios where public.usuario_rol_normalizado(rol_usuario) in('administracion','director_nacional') loop insert into public.notificaciones(usuario_auth_id,tipo,titulo,mensaje,entidad_tipo,datos,leida,enviada_push,creado_en)values(u.auth_id,'cambio_rol','Contrato firmado pendiente','Hay un cambio de figura pendiente de visto bueno.','cambio_rol',jsonb_build_object('cambio_rol_id',c.id),false,false,now());end loop;return c;end$$;
create or replace function public.cambio_rol_resolver(p_id uuid,p_aprobar boolean,p_observaciones text default null) returns public.cambios_rol language plpgsql security definer set search_path='' as $$declare c public.cambios_rol%rowtype;actor_id uuid;begin if not public.app_can_manage_global() then raise exception 'Accion reservada a Administracion o Direccion Nacional';end if;select id into actor_id from public.usuarios where auth_id=auth.uid() limit 1;select * into c from public.cambios_rol where id=p_id for update;if c.id is null or c.estado<>'FIRMADO_PENDIENTE_VALIDACION' then raise exception 'No hay una firma pendiente de validar';end if;if p_aprobar then update public.usuarios set rol_usuario=c.rol_nuevo,parent_id=c.parent_nuevo_id where id=c.usuario_id;update public.cambios_rol set estado='APROBADO',aprobado_at=now(),aprobado_por_usuario_id=actor_id,observaciones=null,updated_at=now() where id=p_id returning * into c;else if nullif(trim(p_observaciones),'') is null then raise exception 'Debes indicar el motivo';end if;update public.cambios_rol set estado='CORRECCION_REQUERIDA',observaciones=trim(p_observaciones),updated_at=now() where id=p_id returning * into c;end if;insert into public.notificaciones(usuario_auth_id,tipo,titulo,mensaje,entidad_tipo,datos,leida,enviada_push,creado_en)values(c.candidato_auth_id,'cambio_rol',case when p_aprobar then 'Cambio de figura aprobado' else 'Correccion de contrato requerida' end,case when p_aprobar then 'Tu nueva figura ya esta activa en SafeBrok.' else c.observaciones end,'cambio_rol',jsonb_build_object('cambio_rol_id',c.id),false,false,now());return c;end$$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('cambios-rol','cambios-rol',false,15728640,array['application/pdf','image/jpeg','image/png','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists cambios_rol_storage_select on storage.objects;create policy cambios_rol_storage_select on storage.objects for select to authenticated using(bucket_id='cambios-rol' and exists(select 1 from public.cambios_rol c where c.id::text=(storage.foldername(name))[1] and(public.app_can_manage_global() or c.candidato_auth_id=auth.uid())));
drop policy if exists cambios_rol_storage_insert on storage.objects;create policy cambios_rol_storage_insert on storage.objects for insert to authenticated with check(bucket_id='cambios-rol' and exists(select 1 from public.cambios_rol c where c.id::text=(storage.foldername(name))[1] and(public.app_can_manage_global() or c.candidato_auth_id=auth.uid())));
alter table public.usuarios_accesos_auditoria drop constraint if exists usuarios_accesos_auditoria_accion_check;alter table public.usuarios_accesos_auditoria add constraint usuarios_accesos_auditoria_accion_check check(accion in('create','update_assignment','request_role_change','deactivate','reactivate','resend_access'));
revoke all on public.cambios_rol from public,anon,authenticated;grant select on public.cambios_rol to authenticated;
revoke all on function public.cambio_rol_publicar_contrato(uuid,text,text),public.cambio_rol_enviar_firmado(uuid,text,text),public.cambio_rol_resolver(uuid,boolean,text) from public,anon;grant execute on function public.cambio_rol_publicar_contrato(uuid,text,text),public.cambio_rol_enviar_firmado(uuid,text,text),public.cambio_rol_resolver(uuid,boolean,text) to authenticated;
commit;